# Generated by Django 4.1 on 2023-07-05 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('davur', '0002_cart_alter_product_review_customer_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
