# Generated by Django 4.1 on 2023-07-05 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('davur', '0004_remove_cart_complete_alter_category_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='availability',
        ),
        migrations.AddField(
            model_name='product',
            name='product_qty',
            field=models.IntegerField(default=0),
        ),
    ]
