# Generated by Django 4.1 on 2023-07-07 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('davur', '0006_customer_order_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='buy_qty',
            field=models.IntegerField(default=0),
        ),
    ]
