# Generated by Django 4.1 on 2023-07-08 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('davur', '0007_product_buy_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
