# Generated by Django 4.1 on 2023-07-08 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('davur', '0009_alter_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
