# Generated by Django 4.1 on 2023-07-09 01:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('davur', '0010_alter_order_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant_review',
            old_name='review',
            new_name='review_content',
        ),
        migrations.RemoveField(
            model_name='restaurant_review',
            name='customer_name',
        ),
        migrations.AddField(
            model_name='restaurant_review',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='davur.customer'),
        ),
        migrations.AlterField(
            model_name='restaurant_review',
            name='rating',
            field=models.IntegerField(),
        ),
    ]
