# Generated by Django 4.1 on 2023-07-09 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('davur', '0011_rename_review_restaurant_review_review_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant_review',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
