# Generated by Django 4.1 on 2023-07-09 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('davur', '0012_category_slug_alter_restaurant_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_qty',
            field=models.IntegerField(),
        ),
    ]
