# Generated by Django 4.1 on 2023-07-10 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('davur', '0013_alter_product_product_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='join_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='last_order_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='total_spent',
            field=models.FloatField(default=0),
        ),
    ]
