# Generated by Django 4.1 on 2023-07-10 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('davur', '0014_customer_join_date_customer_last_order_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='join_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
