# Generated by Django 4.1 on 2023-07-14 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('davur', '0016_onlinecustomer_shippingaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlinecustomer',
            name='email',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
