# Generated by Django 4.1 on 2023-07-15 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('davur', '0022_remove_shippingaddress_country_shippingaddress_zip_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, null=True)),
                ('value', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='nullitemonl',
            name='cart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nullitem', to='davur.cartonl'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='mobile',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='zip',
            field=models.IntegerField(null=True),
        ),
    ]
