# Generated by Django 4.1 on 2023-07-16 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('davur', '0023_discount_alter_nullitemonl_cart_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartonl',
            name='discount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='customerhistory',
            name='buy_qty',
            field=models.IntegerField(default=0),
        ),
    ]
