# Generated by Django 4.1 on 2023-07-16 08:35

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('davur', '0024_cartonl_discount_alter_customerhistory_buy_qty'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CartItemOnl',
            new_name='CartItemOnline',
        ),
        migrations.RenameModel(
            old_name='CartOnl',
            new_name='CartOnline',
        ),
        migrations.RenameModel(
            old_name='ListOrderOnl',
            new_name='ListOrderOnline',
        ),
        migrations.RenameModel(
            old_name='NullItemOnl',
            new_name='NullItemOnline',
        ),
        migrations.RenameModel(
            old_name='OrderOnl',
            new_name='OrderOnline',
        ),
    ]
