# Generated by Django 4.1 on 2023-07-16 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('davur', '0027_orderstatus_customer_alter_orderstatus_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderstatus',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='orderstatus',
            name='order',
        ),
        migrations.AddField(
            model_name='orderonline',
            name='order_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='davur.orderstatus'),
        ),
    ]
