# Generated by Django 4.1 on 2023-07-16 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('davur', '0029_rename_is_complete_orderonline_is_paid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product_review',
            old_name='review',
            new_name='review_content',
        ),
        migrations.AlterField(
            model_name='orderonline',
            name='order_status',
            field=models.CharField(choices=[('Order Placed', 'Order Placed'), ('In Transit', 'In Transit'), ('Delivered', 'Delivered'), ('Completed', 'Completed')], default='Order Placed', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product_review',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
