# Generated by Django 4.1 on 2023-07-16 19:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('davur', '0031_alter_product_review_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listorderonline',
            name='product_name',
        ),
        migrations.RemoveField(
            model_name='listorderonline',
            name='product_price',
        ),
        migrations.AddField(
            model_name='listorderonline',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='listorderonline',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='davur.product'),
        ),
    ]
