# Generated by Django 4.1 on 2023-07-16 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('davur', '0032_remove_listorderonline_product_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderonline',
            name='order_status',
            field=models.CharField(choices=[('Order Placed', 'Order Placed'), ('Packed', 'Packed'), ('In Transit', 'In Transit'), ('Delivered', 'Delivered'), ('Completed', 'Completed')], default='Order Placed', max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='OrderTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_placed', models.DateTimeField(auto_now_add=True)),
                ('time_packed', models.DateTimeField(null=True)),
                ('time_transit', models.DateTimeField(null=True)),
                ('time_delivery', models.DateTimeField(null=True)),
                ('order', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='davur.orderonline')),
            ],
        ),
    ]
