# Generated by Django 4.1 on 2023-07-17 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('davur', '0033_alter_orderonline_order_status_ordertracking'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilterDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filter_date', models.DateField(default=None)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='filter_date',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filterdate', to='davur.filterdate'),
        ),
    ]
