# Generated by Django 4.1 on 2023-07-17 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('davur', '0034_filterdate_order_filter_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemoDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demo', models.DateField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='DemoOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('demo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='davur.demodate')),
            ],
        ),
    ]
